name: Weekly Analytics Report

on:
  schedule:
    # Runs every Monday at 9:00 AM Central Time (14:00 UTC)
    - cron: '0 14 * * 1'
  workflow_dispatch: # Allow manual trigger

jobs:
  send-weekly-report:
    runs-on: ubuntu-latest
    steps:
      - name: Send Weekly Analytics Report
        run: |
          curl -X POST "${{ secrets.APP_URL }}/api/weekly-report" \
            -H "Content-Type: application/json" \
            -w "HTTP Status: %{http_code}\n" \
            -s